name: Release Windows x86

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
      - name: Install dev requirements
        run: pipenv install --dev
      - name: Build
        run: pipenv run build_windows_x86
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: ./dist/configure_repositories_windows_x86.exe
